sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.java.test.binaries=app/build/tmp/kotlin-classes/debugUnitTest
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest
sonar.sourceEncoding=UTF-8
